# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kagent/api/v1alpha1/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'kagent/api/v1alpha1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n kagent/api/v1alpha1/common.proto\x12\x13kagent.api.v1alpha1\x1a\x1b\x62uf/validate/validate.proto\"\xda\x01\n\tWorkspace\x12!\n\x04repo\x18\x01 \x01(\tB\r\xbaH\nr\x08\x10\x01\x18\x80\x10\x88\x01\x01R\x04repo\x12@\n\x03ref\x18\x02 \x01(\tB.\xbaH+r)\x18\xff\x01\x32$^(?:$|[A-Za-z0-9_][A-Za-z0-9._/-]*)$R\x03ref\x12\x46\n\x06\x62ranch\x18\x03 \x01(\tB.\xbaH+r)\x18\xff\x01\x32$^(?:$|[A-Za-z0-9_][A-Za-z0-9._/-]*)$R\x06\x62ranch\x12 \n\x05\x64\x65pth\x18\x04 \x01(\x05\x42\n\xbaH\x07\x1a\x05\x18\xe8\x07(\x00R\x05\x64\x65pthBIZGgithub.com/kagent-dev/kagent/go/api/gen/kagent/api/v1alpha1;apiv1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kagent.api.v1alpha1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZGgithub.com/kagent-dev/kagent/go/api/gen/kagent/api/v1alpha1;apiv1alpha1'
  _globals['_WORKSPACE'].fields_by_name['repo']._loaded_options = None
  _globals['_WORKSPACE'].fields_by_name['repo']._serialized_options = b'\272H\nr\010\020\001\030\200\020\210\001\001'
  _globals['_WORKSPACE'].fields_by_name['ref']._loaded_options = None
  _globals['_WORKSPACE'].fields_by_name['ref']._serialized_options = b'\272H+r)\030\377\0012$^(?:$|[A-Za-z0-9_][A-Za-z0-9._/-]*)$'
  _globals['_WORKSPACE'].fields_by_name['branch']._loaded_options = None
  _globals['_WORKSPACE'].fields_by_name['branch']._serialized_options = b'\272H+r)\030\377\0012$^(?:$|[A-Za-z0-9_][A-Za-z0-9._/-]*)$'
  _globals['_WORKSPACE'].fields_by_name['depth']._loaded_options = None
  _globals['_WORKSPACE'].fields_by_name['depth']._serialized_options = b'\272H\007\032\005\030\350\007(\000'
  _globals['_WORKSPACE']._serialized_start=87
  _globals['_WORKSPACE']._serialized_end=305
# @@protoc_insertion_point(module_scope)
